# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
import numpy as np
a = np.loadtxt('data\minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
a[0:5,]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
print('Второй столбец:')
print('Среднее значение:', np.mean(a[:, 1]))
print('Минимум:', min(a[:, 1]))
print('Максимум:', max(a[:, 1]))
print('Медиана:', np.median(a[:, 1]))
print('Третий столбец:')
print('Среднее значение:', np.mean(a[:, 2]))
print('Минимум:', min(a[:, 2]))
print('Максимум:', max(a[:, 2]))
print('Медиана:', np.median(a[:, 2]))

Второй столбец:
Среднее значение: 21601.00169
Минимум: 0
Максимум: 2147483647
Медиана: 40.0
Третий столбец:
Среднее значение: 9.05528
Минимум: 1
Максимум: 39
Медиана: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
q = np.quantile(a[:, 1], q=0.75)
a[:, 1] = a[:, 1].clip(max=q)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [5]:
np.count_nonzero(a[:, 1] == 0)


479

In [6]:
np.place(a[:, 1], a[:, 1] == 0, 1)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [7]:
len(np.unique(a, axis=0))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [8]:
np.column_stack(np.unique(a[:, 2], return_counts=True))

array([[    1,    13],
       [    2,   926],
       [    3,  2895],
       [    4,  5515],
       [    5,  7913],
       [    6,  9376],
       [    7, 10628],
       [    8, 10951],
       [    9, 10585],
       [   10,  9591],
       [   11,  8297],
       [   12,  6605],
       [   13,  4997],
       [   14,  3663],
       [   15,  2595],
       [   16,  1767],
       [   17,  1246],
       [   18,   790],
       [   19,   573],
       [   20,   376],
       [   21,   217],
       [   22,   161],
       [   23,   105],
       [   24,    69],
       [   25,    50],
       [   26,    28],
       [   27,    16],
       [   28,    16],
       [   29,    12],
       [   30,    12],
       [   31,     3],
       [   32,     1],
       [   33,     2],
       [   34,     1],
       [   35,     3],
       [   37,     1],
       [   39,     1]], dtype=int64)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [9]:
lessfive = a[a[:, 2] <= 5]
lessfive

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [112]:
max(a[:, 2]/a[:, 1])

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [113]:
top = a[a[:, 1].argsort()[::-1]]
np.mean(top[:100, 2])

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [126]:
i = np.random.randint(len(np.unique(a, axis=0)), size=10)
a[i,:]

array([[206837,     55,      5],
       [184843,     40,     12],
       [338632,     20,      6],
       [ 27764,     40,      7],
       [169600,     45,     12],
       [ 78188,     30,     11],
       [ 57491,     65,      5],
       [133496,     25,     10],
       [254519,      2,      4],
       [401203,     15,      4]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [128]:
lessmean = a[a[:, 2] <= np.mean(a[:, 2])]
len(lessmean)/len(a)*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [140]:
easy = np.where((a[:, 1] <= 20) & (a[:, 2] <= 5), 1, 0)
easya = np.column_stack((a, easy))

13. Выведите процент "простых" рецептов в датасете

In [141]:
np.count_nonzero(easya[:, 3] == 1)/len(a)*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [178]:
short = a[a[:, 1] < 10]
standart = a[(a[:, 1] >= 10)&(a[:, 1] < 20)]
long  = a[a[:, 1] >= 20]
y = min(len(short),len(standart),len(long))
threeda = np.stack((short[0:y,], standart[0:y,], long[0:y,]))
np.shape(threeda)
#threeda[0:5,]


(3, 7588, 3)